name: PlasmixGave
version: '1.0.0'
main: ru.kseonyt.plasmixgave.PlasmixGave
api-version: '1.16'
author: KSEONYT

commands:
  plasmixgave:
    usage: /plasmixgave <check|reload|info|debug>
    permission: plasmixgave.admin
    aliases: [pgave]

permissions:
  plasmixgave.admin:
    default: op
